#! /bin/bash
mkdir -r logs
FILE="logs/genlin.`date +%s`.out"
echo "=============== TTT TOURNEMENT ================"
time echo -e ":q\n0.97\n:t\n100000"| ./GENLIN | tee logs/final/ttt-tournement.log
echo "=============== TTT ROULETTE =================="
time echo -e "1\n100\n:q\n0.97\n:r\n100000"| ./GENLIN | tee logs/final/ttt-roulette.log
echo "=============== TTT GREEDY ROULETTE =============="
time echo -e "1\n100\n:q\n0.97\n:g\n100000"| ./GENLIN | tee logs/final/ttt-greedy.log
echo "=============== IRIS TOURNEMENT ================="
time echo -e "3\n:iris\n:q\n0.97\n:t\n100000"| ./GENLIN | tee logs/final/iris-tournement.log
echo "=============== IRIS ROULETTE =================="
time echo -e "3\n:iris\n:c\n1\n100\n:q\n0.97\n:r\n100000"| ./GENLIN | tee logs/final/iris-roulette.log
echo "=============== IRIS GREEDY ROULETTE ============="
time echo -e "3\n:iris\n:c\n1\n100\n:q\n0.97\n:g\n100000"| ./GENLIN | tee logs/final/iris-greedy.log






